<?php

namespace NutricionBundle\Repository;

/**
 * PeriodocierreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodocierreRepository extends \Doctrine\ORM\EntityRepository
{
}
