<?php

namespace NutricionBundle\Repository;

/**
 * PlanillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanillaRepository extends \Doctrine\ORM\EntityRepository
{
}
