<?php

namespace NutricionBundle\Repository;

/**
 * VolumenesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolumenesRepository extends \Doctrine\ORM\EntityRepository
{
}
