nutricion:
    resource: "@NutricionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation